const mongoose=require("mongoose")

const userSchema=mongoose.Schema({
    Name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    otpCode:{
        type:String
    },
    phone:{
        type:Number,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    is_admin:{
        type:Number
    },
    is_verified:{
        type:Boolean,
        default:false
    },
    referral_code:{
        type:Number,
    },
    createdOn:{
        type:String
    },
    is_blocked:{
        type:Boolean,
        default:false
    },
    wishlist:[
        {
            productId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'product'
            }
        }
    ],
    cart:[
        {
            productId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'product'
            },
            quantity:{
                type:Number,
                
            },
            size:{
                type:String
            }
        }
    ],
    address:[
        {
            name:{
                type:String
            },
            mobile:{
                type:Number
            },
            housename:{
                type:String
            },
            area:{
                type:String
            },
            city:{
                type:String
            },
            state:{
                type:String
            },
            pincode:{
                type:Number
            },
            active:{
                type:Boolean,
                default:false
            }
        }
    ],
    wallet:{
        type:Number,
        default:0
    },
    transactionDetails:[{
            transactionType:{
                type:String
            },
            transactionAmount:{
                type:Number
            },
            transactionDate:{
                typr:Date
            },
            orderId:{
                type:mongoose.Schema.Types.ObjectId
            }
        
    }]
})

module.exports=mongoose.model("user",userSchema)